import test from 'node:test';import assert from 'node:assert/strict';import {generateKeyPairSync,sign,verify,createPublicKey} from 'node:crypto';import {appleClientSecret,verifyAppleToken} from './apple-oauth.mjs';import {createApp} from './app.mjs';import {openTestDatabase} from './test-database.mjs';import {hashPassword} from './database.mjs';
const ec=generateKeyPairSync('ec',{namedCurve:'P-256'}),rsa=generateKeyPairSync('rsa',{modulusLength:2048});const key={...rsa.publicKey.export({format:'jwk'}),kid:'apple-key',alg:'RS256',use:'sig'};
const config={appUrl:'https://villacheck.test',allowedOrigins:['https://villacheck.test'],secureCookies:true,fakeHash:hashPassword('placeholder'),appleClientId:'com.villacheck.web',appleTeamId:'TEAM123',appleKeyId:'KEY123',applePrivateKey:ec.privateKey.export({format:'pem',type:'pkcs8'})};
function token(claims){const input=[{alg:'RS256',kid:key.kid},claims].map(x=>Buffer.from(JSON.stringify(x)).toString('base64url')).join('.');return input+'.'+sign('RSA-SHA256',Buffer.from(input),rsa.privateKey).toString('base64url')}
test('Apple client secret is ES256 and ID tokens reject bad signature, issuer, audience, expiry and nonce',()=>{
 const secret=appleClientSecret(config);const parts=secret.split('.');assert.equal(JSON.parse(Buffer.from(parts[1],'base64url')).sub,config.appleClientId);assert.ok(verify('sha256',Buffer.from(parts.slice(0,2).join('.')),{key:ec.publicKey,dsaEncoding:'ieee-p1363'},Buffer.from(parts[2],'base64url')));
 const claims={iss:'https://appleid.apple.com',aud:config.appleClientId,nonce:'nonce',iat:Math.floor(Date.now()/1000),exp:Math.floor(Date.now()/1000)+600,sub:'apple-user'};
 assert.equal(verifyAppleToken(token(claims),{keys:[key]},config.appleClientId,'nonce').sub,'apple-user');for(const bad of [{iss:'evil'},{aud:'wrong'},{nonce:'wrong'},{exp:0}])assert.throws(()=>verifyAppleToken(token({...claims,...bad}),{keys:[key]},config.appleClientId,'nonce'));
 assert.throws(()=>verifyAppleToken(token(claims).slice(0,-12)+'AAAAAAAAAAAA',{keys:[key]},config.appleClientId,'nonce'));
});
test('Apple form POST creates only User, accepts relay emails and repeat login, rejects missing cookie and replay',async t=>{
 const db=await openTestDatabase();let nonce,subject='apple-relay-user',address='dummy@privaterelay.appleid.com';const app=createApp(db,{...config,oauthFetch:async url=>({ok:true,json:async()=>String(url).endsWith('/keys')?{keys:[key]}:{access_token:'apple-token',id_token:token({iss:'https://appleid.apple.com',aud:config.appleClientId,sub:subject,email:address,email_verified:'true',nonce,iat:Math.floor(Date.now()/1000),exp:Math.floor(Date.now()/1000)+600})}})});await new Promise(r=>app.listen(0,'127.0.0.1',r));t.after(async()=>{await new Promise(r=>app.close(r));await db.close()});const base=`http://127.0.0.1:${app.address().port}`;
 const start=async()=>{const r=await fetch(base+'/api/auth/oauth/apple/start',{redirect:'manual'});const u=new URL(r.headers.get('location'));nonce=u.searchParams.get('nonce');assert.equal(u.hostname,'appleid.apple.com');assert.equal(u.searchParams.get('response_mode'),'form_post');assert.match(r.headers.get('set-cookie'),/SameSite=None/);assert.match(r.headers.get('set-cookie'),/Secure/);return{state:u.searchParams.get('state'),cookie:r.headers.get('set-cookie').split(';')[0]}};
 const callback=(f,cookie=f.cookie)=>fetch(base+'/api/auth/oauth/apple/callback',{method:'POST',redirect:'manual',headers:{'Content-Type':'application/x-www-form-urlencoded',Cookie:cookie},body:new URLSearchParams({state:f.state,code:'apple-code',user:JSON.stringify({name:{firstName:'Apple',lastName:'Member'}})}).toString()});
 const first=await start();assert.match((await callback(first,'')).headers.get('location'),/invalid_state/);const success=await callback(first);assert.equal(success.headers.get('location'),'https://villacheck.test/#page=user-dashboard');assert.match(success.headers.get('set-cookie'),/vc_session=/);const user=await db.prepare('SELECT * FROM users WHERE email=?').get(address);assert.equal(user.role,'user');assert.equal(user.name,'Apple Member');assert.match((await callback(first)).headers.get('location'),/invalid_state/);
 address=undefined;const repeat=await start();assert.match((await callback(repeat)).headers.get('set-cookie'),/vc_session=/);
 subject='different-subject';address='dummy@privaterelay.appleid.com';const collision=await start();assert.match((await callback(collision)).headers.get('location'),/email_exists/);
});
