CREATE TABLE IF NOT EXISTS package_catalog (
 id TEXT PRIMARY KEY, name TEXT NOT NULL, slug TEXT NOT NULL UNIQUE, description TEXT NOT NULL,
 amount INTEGER NOT NULL CHECK(amount>=0), currency TEXT NOT NULL DEFAULT 'THB', billing_cycle TEXT NOT NULL DEFAULT 'MONTHLY',
 trial_months INTEGER NOT NULL DEFAULT 0 CHECK(trial_months>=0), capacity INTEGER NOT NULL CHECK(capacity>=1),
 features TEXT NOT NULL DEFAULT '[]', max_level TEXT NOT NULL DEFAULT 'VERIFIED', banner INTEGER NOT NULL DEFAULT 0,
 active INTEGER NOT NULL DEFAULT 1, sort_order INTEGER NOT NULL DEFAULT 0, created TEXT NOT NULL, updated TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS system_settings (key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS leads (
 id TEXT PRIMARY KEY,user_id TEXT UNIQUE REFERENCES users(id),type TEXT NOT NULL CHECK(type IN ('USER','MERCHANT')),
 name TEXT NOT NULL,email TEXT NOT NULL,phone TEXT NOT NULL DEFAULT '',source TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'NEW',
 notes TEXT NOT NULL DEFAULT '',created TEXT NOT NULL,updated TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS payment_qrs (
 id TEXT PRIMARY KEY,payment_id TEXT NOT NULL REFERENCES invoices(id),payload TEXT NOT NULL,
 generated_at TEXT NOT NULL,expires_at TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('ACTIVE','PAID','EXPIRED','CANCELLED')),
 created TEXT NOT NULL,updated TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS one_active_payment_qr ON payment_qrs(payment_id) WHERE status='ACTIVE';
