import test from 'node:test';import assert from 'node:assert/strict';import {createLoginOtp,otpChannels,otpDestination} from './login-otp.mjs';import {openTestDatabase} from './test-database.mjs';import {createUser} from './database.mjs';
const config={otpSecret:'a-secure-test-secret-with-over-32-characters',smtpFrom:'noreply@example.com',thaiBulkSmsApiKey:'test-key',thaiBulkSmsApiSecret:'test-secret',thaiBulkSmsSender:'VillaCheck'};
test('OTP normalizes Thai phones and disables unconfigured delivery',()=>{assert.equal(otpDestination('sms','081 234 5678'),'+66812345678');assert.equal(otpDestination('email',' User@Example.com '),'user@example.com');assert.throws(()=>otpDestination('sms','hello'));assert.deepEqual(otpChannels({},null),{email:false,sms:false})});
test('Email OTP hashes codes, expires, consumes once, limits mistakes and preserves existing role',async t=>{
 const db=await openTestDatabase();t.after(()=>db.close());const sent=[];const otp=createLoginOtp(db,config,{sendMail:async m=>sent.push(m)});const code=()=>sent.at(-1).text.match(/\d{6}/)[0];const existing=await createUser(db,'merchant-otp@example.com','Password12345','Merchant','merchant');
 const first=await otp.request({channel:'email',destination:existing.email});const saved=await db.prepare('SELECT * FROM login_otps WHERE id=?').get(first.challengeId);assert.notEqual(saved.code_hash,code());assert.ok(!JSON.stringify(first).includes(code()));assert.equal((await otp.verify({challengeId:first.challengeId,code:code()})).id,existing.id);await assert.rejects(()=>otp.verify({challengeId:first.challengeId,code:code()}),/OTP/);
 const next=await otp.request({channel:'email',destination:'new@example.com'});const valid=code();for(let i=0;i<5;i++)await assert.rejects(()=>otp.verify({challengeId:next.challengeId,code:valid==='000000'?'111111':'000000'}),/OTP/);assert.equal((await db.prepare('SELECT attempts FROM login_otps WHERE id=?').get(next.challengeId)).attempts,5);await assert.rejects(()=>otp.verify({challengeId:next.challengeId,code:valid}),/OTP/);
 const expired=await otp.request({channel:'email',destination:'expired@example.com'});await db.prepare('UPDATE login_otps SET expires=0 WHERE id=?').run(expired.challengeId);await assert.rejects(()=>otp.verify({challengeId:expired.challengeId,code:code()}),/OTP/);
});
test('OTP resend invalidates old codes; cooldown and delivery failure are enforced',async t=>{
 const db=await openTestDatabase();t.after(()=>db.close());let text;const otp=createLoginOtp(db,config,{sendMail:async m=>{text=m.text}});const first=await otp.request({channel:'email',destination:'repeat@example.com'});const old=text.match(/\d{6}/)[0];await assert.rejects(()=>otp.request({channel:'email',destination:'repeat@example.com'}),/60/);await db.prepare('UPDATE login_otps SET created=? WHERE id=?').run(Date.now()-61000,first.challengeId);const second=await otp.request({channel:'email',destination:'repeat@example.com'});await assert.rejects(()=>otp.verify({challengeId:first.challengeId,code:old}),/OTP/);const user=await otp.verify({challengeId:second.challengeId,code:text.match(/\d{6}/)[0]});assert.equal(user.role,'user');
 const bad=createLoginOtp(db,config,{sendMail:async()=>{throw Error('private SMTP secret')}});await assert.rejects(()=>bad.request({channel:'email',destination:'failed@example.com'}),e=>e.status===503&&!e.message.includes('secret'));assert.equal((await db.prepare('SELECT consumed FROM login_otps WHERE destination=?').get('failed@example.com')).consumed,1);
});
test('SMS OTP creates verified User identity without adopting Merchant contact phone',async t=>{
 const db=await openTestDatabase();t.after(()=>db.close());const merchant=await createUser(db,'phone-merchant@example.com','Password12345','Merchant','merchant');await db.prepare('UPDATE users SET phone=? WHERE id=?').run('+66812345678',merchant.id);let code;const otp=createLoginOtp(db,config,null,async(url,options)=>{assert.match(String(url),/api-v2.thaibulksms.com/);const p=new URLSearchParams(options.body);assert.equal(p.get('msisdn'),'66812345678');assert.equal(p.get('sender'),'VillaCheck');assert.equal(options.headers.Authorization,'Basic '+Buffer.from('test-key:test-secret').toString('base64'));code=p.get('message').match(/\d{6}/)[0];return {ok:true,json:async()=>({phone_number_list:[{number:'66812345678',message_id:'message-123'}],bad_phone_number_list:[]})}});const first=await otp.request({channel:'sms',destination:'0812345678'});const user=await otp.verify({challengeId:first.challengeId,code});assert.equal(user.role,'user');assert.notEqual(user.id,merchant.id);await db.prepare('UPDATE login_otps SET created=? WHERE id=?').run(Date.now()-61000,first.challengeId);const repeat=await otp.request({channel:'sms',destination:'+66812345678'});assert.equal((await otp.verify({challengeId:repeat.challengeId,code})).id,user.id);
});

test('HTTP OTP enforces same origin, exposes no codes and establishes a usable session',async t=>{
 const {createApp}=await import('./app.mjs');const {hashPassword}=await import('./database.mjs');const db=await openTestDatabase();let code;const origin='http://localhost:8443';const app=createApp(db,{...config,appUrl:origin,allowedOrigins:[origin],fakeHash:hashPassword('placeholder'),serverless:true},{sendMail:async m=>{code=m.text.match(/\d{6}/)[0]}});await new Promise(r=>app.listen(0,'127.0.0.1',r));t.after(async()=>{await new Promise(r=>app.close(r));await db.close()});const base=`http://127.0.0.1:${app.address().port}`;
 const post=(path,data,from=origin)=>fetch(base+'/api/auth/otp/'+path,{method:'POST',headers:{Origin:from,'Content-Type':'application/json'},body:JSON.stringify(data)});
 assert.equal((await post('request',{channel:'email',destination:'http@example.com'},'https://evil.example')).status,403);
 const request=await post('request',{channel:'email',destination:'http@example.com'});assert.equal(request.status,200);const challenge=await request.json();assert.equal(challenge.code,undefined);const verified=await post('verify',{challengeId:challenge.challengeId,code});assert.equal(verified.status,200);const value=await verified.json();assert.equal(value.user.role,'user');assert.ok(value.csrf);const cookie=verified.headers.get('set-cookie').split(';')[0];const me=await fetch(base+'/api/auth/me',{headers:{Cookie:cookie}});assert.equal(me.status,200);assert.equal((await me.json()).user.email,'http@example.com');assert.equal((await post('verify',{challengeId:challenge.challengeId,code})).status,401);
});

test('ThaiBulkSMS rejects HTTP success without an accepted recipient and invalidates OTP',async t=>{
 const db=await openTestDatabase();t.after(()=>db.close());const otp=createLoginOtp(db,config,null,async()=>({ok:true,json:async()=>({phone_number_list:[],bad_phone_number_list:[{number:'66812345678',message:'invalid'}]})}));await assert.rejects(()=>otp.request({channel:'sms',destination:'0812345678'}),e=>e.status===503);assert.equal((await db.prepare('SELECT consumed FROM login_otps WHERE destination=?').get('+66812345678')).consumed,1);
});

test('HTTP email delivery failure returns safe action message and Admin-only sanitized diagnostics',async t=>{
 const {createApp}=await import('./app.mjs');const {hashPassword}=await import('./database.mjs');const db=await openTestDatabase();await createUser(db,'diagnostic-admin@test.com','AdminPassword123','Admin','admin');const origin='http://localhost:8443';const app=createApp(db,{...config,appUrl:origin,allowedOrigins:[origin],fakeHash:hashPassword('placeholder'),serverless:true},{sendMail:async()=>{throw Object.assign(Error('private SMTP password'),{code:'EAUTH'})}});await new Promise(r=>app.listen(0,'127.0.0.1',r));t.after(async()=>{await new Promise(r=>app.close(r));await db.close()});const base=`http://127.0.0.1:${app.address().port}`;const post=(path,data)=>fetch(base+'/api'+path,{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify(data)});
 const response=await post('/auth/otp/request',{channel:'email',destination:'diagnostic@example.com'});assert.equal(response.status,503);const value=await response.json();assert.match(value.error,/ส่งอีเมล OTP ไม่สำเร็จ/);assert.ok(!value.error.includes('password'));assert.equal((await fetch(base+'/api/admin/otp/status')).status,401);const login=await post('/auth/login',{email:'diagnostic-admin@test.com',password:'AdminPassword123'});const cookie=login.headers.get('set-cookie').split(';')[0];const status=await(await fetch(base+'/api/admin/otp/status',{headers:{Cookie:cookie}})).json();assert.equal(status.email.reason,'SMTP_AUTH_FAILED');assert.ok(!JSON.stringify(status).includes('password'));assert.ok(!JSON.stringify(status).includes('diagnostic@example.com'));
});

test('SMS provider diagnostics classify errors and redact credentials; credit probe never sends SMS',async()=>{
 const {smsDiagnostic,probeSmsCredit}=await import('./login-otp.mjs');
 for(const [status,code,category] of [[403,'ERROR_USER_TRIAL','ERROR_USER_TRIAL'],[423,'ERROR_INSUFFICIENT_CREDIT','ERROR_INSUFFICIENT_CREDIT'],[401,'ERROR_AUTHENTICATION_FAILED','AUTHENTICATION_ERROR'],[400,'ERROR_SENDER','SENDER_OR_CONFIG_ERROR'],[503,'','PROVIDER_SERVER_ERROR']])assert.equal(smsDiagnostic(config,status,{code}).category,category);
 assert.equal(smsDiagnostic(config,400,{code:110,error:{message:'Sender is invalid.'}}).category,'SENDER_OR_CONFIG_ERROR');assert.match(smsDiagnostic(config,400,{code:110,error:{message:'Sender is invalid.'}}).errorMessage,/Sender is invalid/);
 const safe=smsDiagnostic(config,400,{message:'test-key test-secret 0812345678'});assert.ok(!JSON.stringify(safe).includes('test-key'));assert.ok(!JSON.stringify(safe).includes('test-secret'));assert.ok(!JSON.stringify(safe).includes('0812345678'));
 const result=await probeSmsCredit(config,async(url,options)=>{assert.equal(url,'https://api-v2.thaibulksms.com/credit');assert.equal(options.method,undefined);return {ok:true,status:200,json:async()=>({remaining_credit:{standard:0,corporate:10}})}});assert.equal(result.authenticated,true);assert.equal(result.remainingCredit.corporate,10);
});

test('Ready to Use requests and verifies OTP with encrypted server-only token, rejects wrong and replayed codes',async t=>{
 const db=await openTestDatabase();t.after(()=>db.close());const ready={...config,thaiBulkSmsOtpKey:'otp-app-key',thaiBulkSmsOtpSecret:'otp-app-secret',thaiBulkSmsSender:undefined};assert.equal(otpChannels(ready,null).sms,true);assert.equal(otpChannels({...ready,thaiBulkSmsOtpSecret:undefined},null).sms,false);const token='provider-token-private';let verifyCalls=0;
 const otp=createLoginOtp(db,ready,null,async(url,options)=>{const params=new URLSearchParams(options.body);assert.equal(params.get('key'),ready.thaiBulkSmsOtpKey);assert.equal(params.get('secret'),ready.thaiBulkSmsOtpSecret);assert.equal(params.get('sender'),null);assert.ok(String(url).startsWith('https://otp.thaibulksms.com/v2/otp/'));if(String(url).endsWith('/request')){assert.equal(params.get('msisdn'),'66812345678');return {ok:true,status:200,json:async()=>({status:'success',token,refno:'ABC'})}}verifyCalls++;assert.equal(params.get('token'),token);return {ok:true,status:200,json:async()=>({status:params.get('pin')==='654321'?'success':'fail'})}});
 const challenge=await otp.request({channel:'sms',destination:'0812345678'});assert.ok(!JSON.stringify(challenge).includes(token));const saved=await db.prepare('SELECT * FROM login_otps WHERE id=?').get(challenge.challengeId);assert.ok(saved.code_hash.startsWith('tbs:'));assert.ok(!saved.code_hash.includes(token));await assert.rejects(()=>otp.verify({challengeId:challenge.challengeId,code:'111111'}),e=>e.status===401);assert.equal((await db.prepare('SELECT attempts FROM login_otps WHERE id=?').get(challenge.challengeId)).attempts,1);const user=await otp.verify({challengeId:challenge.challengeId,code:'654321'});assert.equal(user.role,'user');await assert.rejects(()=>otp.verify({challengeId:challenge.challengeId,code:'654321'}),e=>e.status===401);assert.equal(verifyCalls,2);
});

test('Email OTP provider uses template and API credentials, encrypts token and preserves account role only after verification',async t=>{
 const db=await openTestDatabase();t.after(()=>db.close());const ready={...config,thaiBulkSmsEmailOtpTemplateId:'template-uuid'};assert.equal(otpChannels(ready,null).email,true);assert.equal(otpChannels({...ready,thaiBulkSmsApiSecret:undefined},null).email,false);const admin=await createUser(db,'email-ready@example.com','Password12345','Admin','admin');const token='private-email-provider-token';let calls=0;const otp=createLoginOtp(db,ready,null,async(url,options)=>{assert.equal(options.headers.Authorization,'Basic '+Buffer.from('test-key:test-secret').toString('base64'));const data=JSON.parse(options.body);if(url.endsWith('/send')){assert.equal(url,'https://email-api.thaibulksms.com/email/v1/otp/send');assert.deepEqual(data,{template_uuid:'template-uuid',recipient_email:admin.email,payload:{}});return {ok:true,status:201,json:async()=>({status:'waiting',token})}}calls++;assert.equal(data.token,token);return {ok:data.otp_code==='123456',status:data.otp_code==='123456'?201:400,json:async()=>({status:data.otp_code==='123456'?'verified':'error',message:data.otp_code==='123456'?'Verified success':'Invalid OTP'})}});const challenge=await otp.request({channel:'email',destination:admin.email});assert.ok(!JSON.stringify(challenge).includes(token));const row=await db.prepare('SELECT * FROM login_otps WHERE id=?').get(challenge.challengeId);assert.ok(row.code_hash.startsWith('tbs:'));assert.ok(!row.code_hash.includes(token));await assert.rejects(()=>otp.verify({challengeId:challenge.challengeId,code:'000000'}),e=>e.status===401);const user=await otp.verify({challengeId:challenge.challengeId,code:'123456'});assert.equal(user.id,admin.id);assert.equal(user.role,'admin');await assert.rejects(()=>otp.verify({challengeId:challenge.challengeId,code:'123456'}),e=>e.status===401);assert.equal(calls,2);
});
test('Email provider credit failure invalidates challenge and records sanitized response',async t=>{
 const db=await openTestDatabase();t.after(()=>db.close());const otp=createLoginOtp(db,{...config,thaiBulkSmsEmailOtpTemplateId:'template'},null,async()=>({ok:false,status:402,json:async()=>({code:'ERROR_INSUFFICIENT_CREDIT',message:'Error insufficient credit'})}));await assert.rejects(()=>otp.request({channel:'email',destination:'credit@example.com'}),e=>e.status===503);assert.equal((await db.prepare('SELECT consumed FROM login_otps WHERE destination=?').get('credit@example.com')).consumed,1);const diagnostic=JSON.parse((await db.prepare("SELECT value FROM system_settings WHERE key='otp_delivery_email'").get()).value);assert.equal(diagnostic.httpStatus,402);assert.equal(diagnostic.category,'ERROR_INSUFFICIENT_CREDIT');
});
