import { useEffect, useState } from "react";
import { api,currentAccount } from "./api";
import { PortalShell,type Page } from "./prototype";
import type { PackagePlan } from "./packagePlans";
type Subscription={owner_id:string;name:string;email:string;package_id:string;lifecycle:string;status:string;expires:string|null};
type Lead={id:string;type:string;name:string;email:string;phone:string;source:string;status:string;notes:string;created:string};
export default function AdminBusiness({page,go}:{page:Page;go:(page:Page)=>void}) {
 const [subscriptions,setSubscriptions]=useState<Subscription[]>([]);
 const [packages,setPackages]=useState<PackagePlan[]>([]),[draft,setDraft]=useState<PackagePlan|null>(null),[leads,setLeads]=useState<Lead[]>([]),[mode,setMode]=useState("MANUAL"),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[query,setQuery]=useState(""),[type,setType]=useState("");
 const load=async()=>{await currentAccount();const [p,l,s]=await Promise.all([api<{packages:PackagePlan[]}>("/admin/packages"),api<{leads:Lead[]}>("/admin/leads"),api<{paymentVerificationMode:string}>("/admin/settings")]);setSubscriptions((await api<{subscriptions:Subscription[]}>("/admin/subscriptions")).subscriptions);setPackages(p.packages);setLeads(l.leads);setMode(s.paymentVerificationMode);};
 useEffect(()=>{void load().catch(e=>setError(e.message));},[]);
 const save=async(path:string,data:unknown)=>{setBusy(true);setError("");try{await api(path,data);await load();setMessage("บันทึกแล้ว");}catch(e){setError(e instanceof Error?e.message:"บันทึกไม่สำเร็จ");}finally{setBusy(false);}};
 const blank=():PackagePlan=>({id:"",name:"",slug:"",description:"",amount:0,capacity:1,currency:"THB",billingCycle:"MONTHLY",trialMonths:0,features:[],maximumVerificationLevel:"VERIFIED",showPremiumBanner:false,isActive:true,sort_order:0});
 return <PortalShell role="Admin" page={page} go={go}><h1>{page==="admin-packages"?"จัดการแพ็กเกจ":page==="admin-leads"?"Lead Management":page==="admin-subscriptions"?"Subscription Management":"System Settings"}</h1>{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
 {page==="admin-packages"&&<section className="merchant-panel"><button className="primary-button" onClick={()=>setDraft(blank())}>เพิ่มแพ็กเกจ</button>{packages.map(p=><div key={p.id} className="button-row"><strong>{p.name} · ฿{p.amount/100} · {p.capacity} Villa · {p.isActive?"เปิด":"ปิด"}</strong><button onClick={()=>setDraft(p)}>แก้ไข</button></div>)}{draft&&<form className="portal-form" onSubmit={e=>{e.preventDefault();void save(draft.id?`/admin/packages/${draft.id}`:"/admin/packages",draft);}}>
 {(["name","slug","description"] as const).map(k=><label key={k}>{k}<input required={k!=="description"} value={draft[k]} onChange={e=>setDraft({...draft,[k]:e.target.value})}/></label>)}
 <label>ราคา THB<input type="number" min="0" step="0.01" value={draft.amount/100} onChange={e=>setDraft({...draft,amount:Math.round(Number(e.target.value)*100)})}/></label>
 {(["capacity","trialMonths","sort_order"] as const).map(k=><label key={k}>{k}<input type="number" min={k==="capacity"?1:0} value={draft[k]} onChange={e=>setDraft({...draft,[k]:Number(e.target.value)})}/></label>)}
 <label>Features (หนึ่งรายการต่อบรรทัด)<textarea value={draft.features.join("\n")} onChange={e=>setDraft({...draft,features:e.target.value.split("\n")})}/></label>
 <label>Maximum Verification Level<select value={draft.maximumVerificationLevel} onChange={e=>setDraft({...draft,maximumVerificationLevel:e.target.value})}>{["REGISTERED","BASIC_CHECKED","VERIFIED","PREMIUM_VERIFIED"].map(x=><option key={x}>{x}</option>)}</select></label>
 <label><input type="checkbox" checked={draft.showPremiumBanner} onChange={e=>setDraft({...draft,showPremiumBanner:e.target.checked})}/>Premium Banner entitlement</label><label><input type="checkbox" checked={draft.isActive} onChange={e=>setDraft({...draft,isActive:e.target.checked})}/>เปิดใช้งาน</label><p>Currency: THB · Billing cycle: MONTHLY</p><button disabled={busy} className="primary-button">บันทึกแพ็กเกจ</button></form>}</section>}
 {page==="admin-leads"&&<section className="merchant-panel"><input placeholder="ค้นหาชื่อ อีเมล เบอร์โทร" value={query} onChange={e=>setQuery(e.target.value)}/><select value={type} onChange={e=>setType(e.target.value)}><option value="">ทุกประเภท</option><option>USER</option><option>MERCHANT</option></select>{leads.filter(l=>(!type||l.type===type)&&`${l.name} ${l.email} ${l.phone}`.toLowerCase().includes(query.toLowerCase())).map(l=><article key={l.id}><h3>{l.name} · {l.type}</h3><p>{l.email} · {l.phone} · {l.source} · {new Date(l.created).toLocaleString("th-TH")}</p><select value={l.status} onChange={e=>setLeads(rows=>rows.map(x=>x.id===l.id?{...x,status:e.target.value}:x))}>{["NEW","CONTACTED","QUALIFIED","CLOSED"].map(x=><option key={x}>{x}</option>)}</select><textarea aria-label="Notes" value={l.notes} onChange={e=>setLeads(rows=>rows.map(x=>x.id===l.id?{...x,notes:e.target.value}:x))}/><button disabled={busy} onClick={()=>void save(`/admin/leads/${l.id}`,{status:l.status,notes:l.notes})}>บันทึก</button></article>)}</section>}
 {page==="admin-subscriptions"&&<section className="merchant-panel">{subscriptions.map(s=><article key={s.owner_id}><h3>{s.name}</h3><p>{s.email} · {s.package_id} · {s.status} · {s.expires||"รอเปิดใช้งาน"}</p>{["ACTIVE","SUSPENDED","CANCELLED"].map(status=><button disabled={busy} key={status} onClick={()=>void save(`/admin/subscriptions/${s.owner_id}`,{status})}>{status}</button>)}</article>)}</section>}
 {page==="admin-settings"&&<section className="merchant-panel"><label><input type="checkbox" checked={mode==="AUTO"} onChange={e=>setMode(e.target.checked?"AUTO":"MANUAL")}/>Auto Payment Verification</label><p>ยังไม่ได้เชื่อมผู้ให้บริการ AUTO ทุกสลิปจะเข้าคิวตรวจ Manual</p><button disabled={busy} className="primary-button" onClick={()=>void save("/admin/settings",{paymentVerificationMode:mode})}>บันทึกการตั้งค่า</button></section>}
 </PortalShell>;
}
