import { useEffect, useState } from "react";
import { api, currentAccount } from "./api";
import { PortalShell, type Page } from "./prototype";
type RecordRow = {id:string;reference?:string;name?:string;villa_name?:string;status?:string;created?:string;detail?:string;result?:string;type?:string;public_note?:string;admin_note?:string;reporter?:string;contact?:string;email?:string;phone?:string;business_name?:string;villa_count?:number;package_id?:string;expires?:string;qr?:string;qrStatus?:string;merchant?:string;verificationLevel?:string;lifecycle?:string;user_name?:string};
type Analytics={totals:{kind:string;total:number}[];daily:{day:string;total:number}[]};
const titles:Record<string,string>={"admin-checks":"ประวัติการตรวจสอบ","admin-reports":"จัดการรายงานปัญหา","admin-owners":"จัดการ Merchant","admin-qr":"จัดการ Villa Verification QR","owner-analytics":"สถิติการใช้งาน 30 วัน","owner-reports":"รายงานเกี่ยวกับ Villa ของคุณ","user-dashboard":"User Dashboard","user-checks":"ประวัติการตรวจสอบ","user-check-detail":"รายละเอียดการตรวจสอบ","user-check-success":"บันทึกการตรวจสอบแล้ว","user-reports":"Report ของฉัน","user-report-detail":"รายละเอียดรายงาน","user-precheck":"ตรวจข้อมูลก่อนโอน"};
const timestamp=(value?:string)=>value?new Date(value).toLocaleString("th-TH",{timeZone:"Asia/Bangkok"}):"—";
export default function OperationsPortal({page,go,item=""}:{page:Page;go:(p:Page,item?:string)=>void;item?:string}){
 const role=page.startsWith("admin-")?"Admin":page.startsWith("owner-")?"Merchant":"User";
 const [rows,setRows]=useState<RecordRow[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[query,setQuery]=useState(""),[filter,setFilter]=useState(""),[selected,setSelected]=useState(""),[stats,setStats]=useState<Analytics>({totals:[],daily:[]});
 const [reports,setReports]=useState<RecordRow[]>([]),[villas,setVillas]=useState<{name:string;qr:string}[]>([]),[form,setForm]=useState({villa:"",account:"",contact:""}),[edit,setEdit]=useState({status:"UNDER_REVIEW",adminNote:"",publicNote:""});
 const [requestKey,setRequestKey]=useState(()=>crypto.randomUUID());
 const path=page==="admin-owners"?"/admin/merchants":page==="admin-qr"?"/admin/qr":page==="owner-analytics"?"/merchant/analytics":page==="owner-reports"?"/merchant/reports":page==="admin-reports"?"/admin/reports":page==="admin-checks"?"/admin/checks":page.includes("report")?"/reports":"/user/checks";
 useEffect(()=>{
  let active=true;setLoading(true);setError("");setRows([]);setSelected("");
  void (async()=>{
   const account=await currentAccount();if(account.role!==role.toLowerCase())throw Error(`หน้านี้สำหรับ ${role}`);
   const data=await api<{checks?:RecordRow[];reports?:RecordRow[];merchants?:RecordRow[];qrs?:RecordRow[];totals?:Analytics["totals"];daily?:Analytics["daily"]}>(path);
   if(!active)return;setRows(data.checks||data.reports||data.merchants||data.qrs||[]);if(data.totals)setStats({totals:data.totals,daily:data.daily||[]});
   if(page==="user-dashboard")setReports((await api<{reports:RecordRow[]}>("/reports")).reports);
   if(page==="user-precheck")setVillas((await api<{villas:{name:string;qr:string}[]}>("/public/villas")).villas);
  })().catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});
  return()=>{active=false};
 },[page,path,role]);
 const save=async(endpoint:string,data:unknown)=>{setBusy(true);setError("");try{await api(endpoint,data);const fresh=await api<{reports?:RecordRow[];qrs?:RecordRow[]}>(path);setRows(fresh.reports||fresh.qrs||[])}catch(e){setError(e instanceof Error?e.message:"บันทึกไม่สำเร็จ")}finally{setBusy(false)}};
 const visible=rows.filter(r=>(!filter||(r.status||r.qrStatus)===filter)&&`${r.reference||""} ${r.name||r.villa_name||""} ${r.email||""}`.toLowerCase().includes(query.toLowerCase()));
 const detail=rows.find(r=>r.reference===item||r.id===item||r.id===selected);
 return <PortalShell role={role} page={page} go={go}><h1>{titles[page]}</h1><p>ข้อมูลล่าสุดจากระบบ · มีรายการสาธิตสำหรับทดสอบ</p>{error&&<p role="alert">{error}</p>}{loading?<p role="status">กำลังโหลด…</p>:<>
 {page==="user-dashboard"?<section className="merchant-panel"><p>ประวัติตรวจสอบ {rows.length} รายการ · Reports {reports.length} รายการ</p><div className="button-row"><button className="primary-button" onClick={()=>go("scan")}>สแกน QR</button><button onClick={()=>go("user-precheck")}>ตรวจข้อมูลก่อนโอน</button><button onClick={()=>go("user-checks")}>ประวัติ Checks</button><button onClick={()=>go("user-reports")}>Report ของฉัน</button></div></section>:
 page==="user-precheck"?<form className="merchant-panel portal-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError("");try{const check=await api<RecordRow>("/user/checks",{...form,requestKey});setRequestKey(crypto.randomUUID());go("user-check-success",check.reference)}catch(e){setError(e instanceof Error?e.message:"ตรวจสอบไม่สำเร็จ")}finally{setBusy(false)}}}>
 <label>ชื่อ Villa<input required value={form.villa} list="check-villas" onChange={e=>setForm({...form,villa:e.target.value})}/><datalist id="check-villas">{villas.map(v=><option key={v.qr} value={v.name}/>)}</datalist></label><label>เลขบัญชีที่ได้รับ<input required value={form.account} onChange={e=>setForm({...form,account:e.target.value})}/></label><label>เบอร์โทรที่ได้รับ<input required value={form.contact} onChange={e=>setForm({...form,contact:e.target.value})}/></label><p>เปรียบเทียบกับทะเบียน VillaCheck เท่านั้น ไม่ได้ตรวจการโอนเงินหรือรับประกันการจอง</p><button className="primary-button" disabled={busy}>{busy?"กำลังตรวจ…":"ตรวจสอบและบันทึก"}</button></form>:
 page==="owner-analytics"?<section className="merchant-panel"><div className="metric-grid">{[["PROFILE_VIEW","เปิดโปรไฟล์"],["QR_SCAN","สแกน QR"],["CONTACT_VIEW","ดูข้อมูลติดต่อ"]].map(([kind,label])=><article key={kind}><h2>{stats.totals.find(r=>r.kind===kind)?.total||0}</h2><p>{label}</p></article>)}</div><h2>จำนวนการใช้งานรายวัน</h2>{stats.daily.map(r=><div key={r.day}><span>{r.day} · {r.total}</span><progress aria-label={r.day} value={r.total} max={Math.max(1,...stats.daily.map(d=>d.total))}/></div>)}{!stats.daily.length&&<p>ยังไม่มีสถิติใน 30 วันที่ผ่านมา</p>}</section>:
 page.includes("detail")||page==="user-check-success"?<section className="merchant-panel">{detail?<><h2>{detail.reference}</h2><p>{detail.villa_name} · {detail.status}</p><p>{detail.result||detail.detail}</p>{detail.public_note&&<p>คำตอบจากทีมงาน: {detail.public_note}</p>}<p>{timestamp(detail.created)}</p>{detail.qr&&<button onClick={()=>go("verify",detail.qr)}>เปิด Trust Profile</button>}</>:<p>ไม่พบรายการนี้ในบัญชีของคุณ</p>}</section>:
 <><div className="merchant-toolbar"><input aria-label="ค้นหา" placeholder="ค้นหาชื่อ เลขอ้างอิง อีเมล" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="กรองสถานะ" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">ทุกสถานะ</option>{[...new Set(rows.map(r=>r.status||r.qrStatus).filter(Boolean))].map(s=><option key={s}>{s}</option>)}</select>{page==="user-reports"&&<button onClick={()=>go("villa-report")}>แจ้งปัญหา</button>}</div>
 {visible.map(r=><article className="merchant-panel" key={r.id}><h2>{r.name||r.villa_name||r.reference}</h2><p>{r.reference} · {r.status||r.qrStatus||r.lifecycle} · {timestamp(r.created)}</p>
 {page==="admin-owners"?<><p>{r.email} · {r.phone||"ไม่ระบุเบอร์"} · {r.villa_count} Villa · แพ็กเกจ {r.package_id||"ยังไม่สมัคร"} · หมดอายุ {timestamp(r.expires)}</p><button onClick={()=>setSelected(selected===r.id?"":r.id)}>รายละเอียด Merchant</button>{selected===r.id&&<p>ชื่อธุรกิจ: {r.business_name||r.name}</p>}</>:
 page==="admin-qr"?<><p>{r.merchant} · {r.verificationLevel} · {r.qr||"รอเปิดใช้ QR"}</p>{r.qr&&<button onClick={()=>go("verify",r.qr)}>เปิดหน้าตรวจสอบ</button>}<div className="button-row">{[["SUSPENDED","ระงับ QR"],["INACTIVE","ปิด QR"],["DEFAULT","ใช้สถานะตามเอกสาร/Subscription"]].map(([status,label])=><button disabled={busy} key={status} onClick={()=>void save(`/admin/qr/${r.id}`,{status})}>{label}</button>)}</div></>:
 <>{page==="admin-checks"&&<p>User: {r.user_name}</p>}<p>{r.result||r.detail}</p>{r.public_note&&<p>คำตอบ: {r.public_note}</p>}{page==="user-checks"&&<button onClick={()=>go("user-check-detail",r.reference)}>รายละเอียด</button>}{page==="user-reports"&&<button onClick={()=>go("user-report-detail",r.reference)}>รายละเอียด</button>}{page==="admin-reports"&&<><p>ผู้แจ้ง: {r.reporter||"ไม่ระบุ"} · ติดต่อ: {r.contact||"ไม่ระบุ"}</p><button onClick={()=>{setSelected(r.id);setEdit({status:r.status||"NEW",adminNote:r.admin_note||"",publicNote:r.public_note||""})}}>ตรวจสอบ/ตอบกลับ</button>{selected===r.id&&<div className="portal-form"><select value={edit.status} onChange={e=>setEdit({...edit,status:e.target.value})}>{["NEW","UNDER_REVIEW","RESOLVED","REJECTED"].map(s=><option key={s}>{s}</option>)}</select><label>บันทึกภายใน Admin<textarea value={edit.adminNote} onChange={e=>setEdit({...edit,adminNote:e.target.value})}/></label><label>คำตอบที่ผู้แจ้งและ Merchant เห็น<textarea value={edit.publicNote} onChange={e=>setEdit({...edit,publicNote:e.target.value})}/></label><button disabled={busy} onClick={()=>void save(`/admin/reports/${r.id}`,edit)}>บันทึก</button></div>}</>}</>}
 </article>)}{!visible.length&&<p>ยังไม่มีรายการ</p>}</>}
 </>}</PortalShell>;
}
